version: '2'

services:
  redis:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - redis
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - dev.env

  generator:
    build:
      context: .
      dockerfile: generator.Dockerfile
    depends_on:
      - redis
    container_name: generator
    env_file:
      - dev.env